project:
  type: website
  output-dir: docs

website:
  title: "RPAS-Field comparison"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: analysis.qmd
        text: Analysis
      - href: prepare_data.qmd
        text: Data
      - icon: github
        href: https://github.com/serpam/rpasveg_alcontar
        aria-label: GitHub repo 
      - icon: twitter
        href: https://twitter.com/SERPAM_EEZ
        aria-label: SERPAM Twitter
        
format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    code-fold: true
    code-tools: true



